### ISSUE TITLE
Zoom changing height of the image

### ISSUE THREAD

**Issue by RSNFreud** [themyth92/ngx-lightbox#63]
Instead of zooming in on the image it makes the image larger which stretches the page downwards... Can it be contained inside a modal that will let it scroll while keeping the window the same height

**Comment by gobicodes** [comment]
Any update this ?

**Comment by pierresh** [comment]
Hello,

I get good results by adding this piece of CSS:

```css
.lb-outerContainer {
	overflow-x: auto;
	overflow-y: auto;
	max-width: calc(100vw - 100px);
	max-height: calc(100vh - 100px);
}
```
